name: address-book-app
version: 0.1
summary: Address Book app
description: Address Book app
confinement: devmode  # use "strict" to enforce system access only via declared interfaces
grade: devel

apps:
    address-book-app:
        command: desktop-launch $SNAP/usr/bin/address-book-app --desktop_file_hint=unity8 "$@"
        plugs: [gsettings, unity7, opengl, platform] # FIXME: add  'address-book' interface after it get merged on snapd

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform
        default-provider: ubuntu-app-platform

parts:
    address-book-app:
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
        source: . 
        build-packages:
            - cmake
            - intltool
            - qt5-default
            - qtbase5-dev
            - qtdeclarative5-dev
            - qtpim5-dev
            - libqofono-dev

        stage-packages:
            - qtdeclarative5-buteo-syncfw0.1
            - qtdeclarative5-gsettings1.0
            - qtdeclarative5-ofono0.2
            - qtdeclarative5-ubuntu-history0.1
            - qtdeclarative5-ubuntu-keyboard-extensions0.1
            - qtdeclarative5-ubuntu-telephony-phonenumber0.1

        stage:
            - -usr/share/pkgconfig/xkeyboard-config.pc
            - -usr/share/pkgconfig/shared-mime-info.pc

        snap:
            - -usr/lib/python3
            - -usr/share/doc
            - -usr/include           

        after: 
            - desktop-ubuntu-app-platform

    environment:
        plugin: dump
        source: snap
